package GUI;

import beans.Radio;
import beans.RadioModel;
import beans.RadioRenderer;

public class GUI extends javax.swing.JFrame
{

  private RadioModel rm = new RadioModel();

  public GUI()
  {
    initComponents();
    jtRadio.setModel(rm);
    jtRadio.setDefaultRenderer(Object.class, new RadioRenderer());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPopupMenu1 = new javax.swing.JPopupMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jScrollPane1 = new javax.swing.JScrollPane();
    jtRadio = new javax.swing.JTable();

    jMenuItem1.setText("hinzufügen");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAddData(evt);
      }
    });
    jPopupMenu1.add(jMenuItem1);

    jMenuItem2.setText("Band ausblenden");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onHide(evt);
      }
    });
    jPopupMenu1.add(jMenuItem2);

    jMenuItem3.setText("Band einblenden");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAdd(evt);
      }
    });
    jPopupMenu1.add(jMenuItem3);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridLayout());

    jScrollPane1.setComponentPopupMenu(jPopupMenu1);

    jtRadio.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jtRadio);

    getContentPane().add(jScrollPane1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onHide(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onHide
  {//GEN-HEADEREND:event_onHide
    rm.updateNumCols(2);
  }//GEN-LAST:event_onHide

  private void onAdd(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAdd
  {//GEN-HEADEREND:event_onAdd
    rm.updateNumCols(3);
  }//GEN-LAST:event_onAdd

  private void onAddData(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAddData
  {//GEN-HEADEREND:event_onAddData
    RadioDialog rd = new RadioDialog(this, true);
    rd.setVisible(true);
    Radio radio = rd.getRadio();
    rm.add(radio);
  }//GEN-LAST:event_onAddData

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new GUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JPopupMenu jPopupMenu1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jtRadio;
  // End of variables declaration//GEN-END:variables
}
